#!/usr/bin/env bash
# transfer file to a remote server


if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assigning parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Using scp to transfer the file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"

# Check if scp command was successful
# if [ $? -eq 0 ]; then
#     echo "File transferred successfully to $IP"
# else
#     echo "Failed to transfer file to $IP"
#     exit 1
# fi

exit 0
