#!/usr/bin/env bash
# Display "Best School" 10 times
counter=0;
while [ "$counter" -lt 10 ]
do
    # Display "Best School" and "Hi" on the 9th iteration"
    if [ "$counter" -eq 9 ]; then
        echo "Hi"
    fi
    echo "Best School"
    ((counter++))
done