#!/bin/bash

# Initialize a counter
counter=1

# Using a while loop to iterate from 1 to 20
while [ $counter -le 20 ]
do
    # Display the current number
    echo $counter

    # Check the loop iteration using a case statement
    case $counter in
    4)
        echo "bad luck from China"
        ;;
    9)
        echo "bad luck from Japan"
        ;;
    17)
        echo "bad luck from Italy"
        ;;
    esac

    # Increment the counter
    ((counter++))
done
